# Docker Compose for Player E2E Integration Tests
#
# This runs the full stack with Flutter integration tests:
# - metadata-relay: Relay service for NAT traversal
# - mydia: Main application
# - player: Flutter web app served via nginx (for manual verification)
# - test: Flutter integration test runner (includes Chrome)
#
# How it works:
# Chrome is installed directly in the test container and controlled by
# Flutter's `flutter test -d chrome` command. This avoids the WebDriver
# complexity and ensures proper integration test binding.
#
# Performance optimizations:
# - BuildKit enabled for cache mounts (DOCKER_BUILDKIT=1)
# - Reduced service dependencies for faster parallel startup
# - Pre-build with: ./dev player e2e-build
#
# Usage:
#   DOCKER_BUILDKIT=1 docker compose -f compose.player-e2e.yml build
#   docker compose -f compose.player-e2e.yml up --abort-on-container-exit
#   docker compose -f compose.player-e2e.yml down -v

services:
  # ============================================
  # Metadata Relay Service
  # ============================================
  relay:
    build:
      context: ./metadata-relay
      dockerfile: Dockerfile
    container_name: e2e_relay
    environment:
      PORT: "4001"
      SQLITE_DB_PATH: /data/relay.db
      LIBP2P_RENDEZVOUS_ENABLED: "true"
      RENDEZVOUS_MASTER_PEPPER: "test-pepper-not-for-production"
      # No API keys needed for E2E tests (not testing metadata fetching)
    volumes:
      - relay_data:/data
    ports:
      - "14001:4001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 2s
      timeout: 2s
      start_period: 5s
      retries: 10
    networks:
      - e2e

  # ============================================
  # Mydia Main Application
  # ============================================
  mydia:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    container_name: e2e_mydia
    environment:
      # Phoenix config
      PHX_HOST: mydia
      PHX_SERVER: "true"
      PORT: "4000"
      HTTPS_PORT: "4443"
      SECRET_KEY_BASE: "E2ETestSecretKeyBase123456789012345678901234567890123456789012345"
      GUARDIAN_SECRET_KEY: "E2ETestGuardianSecretKey12345678901234567890123456789012345678"

      # Database
      DATABASE_PATH: /config/mydia.db
      MIX_ENV: prod

      # Relay connection
      METADATA_RELAY_URL: "http://relay:4001"

      # E2E test mode - auto-enable remote access
      E2E_MODE: "true"
      E2E_ADMIN_EMAIL: "admin@test.local"
      E2E_ADMIN_PASSWORD: "testpassword123"

      # Disable HTTPS origin checks for E2E
      PHX_CHECK_ORIGIN: "false"

      # Direct URLs config for E2E testing
      # Use HTTP instead of HTTPS for sslip.io URLs (required for E2E since we don't have certs)
      EXTERNAL_PORT: "4000"
      PUBLIC_IP_ENABLED: "false"
      DIRECT_URLS_USE_HTTP: "true"
    volumes:
      - mydia_config:/config
      - mydia_data:/data
    ports:
      - "14000:4000"
      - "14443:4443"
    depends_on:
      relay:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 2s
      timeout: 2s
      start_period: 15s
      retries: 20
    networks:
      - e2e

  # ============================================
  # Flutter Web Player (served via nginx)
  # ============================================
  # Note: player doesn't need to depend on mydia - it's just static files
  # The test runner will wait for mydia to be healthy
  player:
    build:
      context: .
      dockerfile: player/Dockerfile.e2e
      args:
        # Bake in the relay URL at build time
        RELAY_URL: "http://relay:4001"
        MYDIA_URL: "http://mydia:4000"
    container_name: e2e_player
    ports:
      - "18080:80"
    # No depends_on - player is just nginx serving static files
    # This allows it to start immediately while other services spin up
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 2s
      timeout: 2s
      start_period: 5s
      retries: 5
    networks:
      - e2e

  # ============================================
  # Flutter Integration Test Runner
  # ============================================
  # The test container includes Chrome and runs tests using
  # `flutter test -d chrome`, which manages Chrome directly.
  test:
    build:
      context: .
      dockerfile: player/Dockerfile.test
    container_name: e2e_test
    environment:
      # Backend service URLs (test container is on the e2e network)
      MYDIA_URL: "http://mydia:4000"
      RELAY_URL: "http://relay:4001"

      # Test admin credentials
      E2E_ADMIN_EMAIL: "admin@test.local"
      E2E_ADMIN_PASSWORD: "testpassword123"
    depends_on:
      mydia:
        condition: service_healthy
      relay:
        condition: service_healthy
    networks:
      - e2e
    # Test runner exits when done

networks:
  e2e:
    driver: bridge

volumes:
  relay_data:
    driver: local
  mydia_config:
    driver: local
  mydia_data:
    driver: local
