// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1908089588;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'mydia_player_p2p',
    ioDirectory: 'rust/mydia_player_p2p/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateP2PHostBootstrap(
      {required P2PHost that, required String addr});

  Future<void> crateP2PHostConnectRelay(
      {required P2PHost that, required String relayAddr});

  Future<void> crateP2PHostDial({required P2PHost that, required String addr});

  Future<FlutterDiscoverResult> crateP2PHostDiscoverNamespace(
      {required P2PHost that, required String namespace});

  Stream<String> crateP2PHostEventStream({required P2PHost that});

  FlutterNetworkStats crateP2PHostGetNetworkStats({required P2PHost that});

  (P2PHost, String) crateP2PHostInit();

  Future<void> crateP2PHostListen(
      {required P2PHost that, required String addr});

  Future<FlutterPairingResponse> crateP2PHostSendPairingRequest(
      {required P2PHost that,
      required String peer,
      required FlutterPairingRequest req});

  Future<void> crateInitApp();

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_P2PHost;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_P2PHost;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_P2PHostPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateP2PHostBootstrap(
      {required P2PHost that, required String addr}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_String(addr, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostBootstrapConstMeta,
      argValues: [that, addr],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostBootstrapConstMeta => const TaskConstMeta(
        debugName: "P2PHost_bootstrap",
        argNames: ["that", "addr"],
      );

  @override
  Future<void> crateP2PHostConnectRelay(
      {required P2PHost that, required String relayAddr}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_String(relayAddr, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostConnectRelayConstMeta,
      argValues: [that, relayAddr],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostConnectRelayConstMeta => const TaskConstMeta(
        debugName: "P2PHost_connect_relay",
        argNames: ["that", "relayAddr"],
      );

  @override
  Future<void> crateP2PHostDial({required P2PHost that, required String addr}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_String(addr, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostDialConstMeta,
      argValues: [that, addr],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostDialConstMeta => const TaskConstMeta(
        debugName: "P2PHost_dial",
        argNames: ["that", "addr"],
      );

  @override
  Future<FlutterDiscoverResult> crateP2PHostDiscoverNamespace(
      {required P2PHost that, required String namespace}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_String(namespace, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_flutter_discover_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostDiscoverNamespaceConstMeta,
      argValues: [that, namespace],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostDiscoverNamespaceConstMeta =>
      const TaskConstMeta(
        debugName: "P2PHost_discover_namespace",
        argNames: ["that", "namespace"],
      );

  @override
  Stream<String> crateP2PHostEventStream({required P2PHost that}) {
    final sink = RustStreamSink<String>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_StreamSink_String_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostEventStreamConstMeta,
      argValues: [that, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateP2PHostEventStreamConstMeta => const TaskConstMeta(
        debugName: "P2PHost_event_stream",
        argNames: ["that", "sink"],
      );

  @override
  FlutterNetworkStats crateP2PHostGetNetworkStats({required P2PHost that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_flutter_network_stats,
        decodeErrorData: null,
      ),
      constMeta: kCrateP2PHostGetNetworkStatsConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostGetNetworkStatsConstMeta =>
      const TaskConstMeta(
        debugName: "P2PHost_get_network_stats",
        argNames: ["that"],
      );

  @override
  (P2PHost, String) crateP2PHostInit() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_p_2_p_host_string,
        decodeErrorData: null,
      ),
      constMeta: kCrateP2PHostInitConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostInitConstMeta => const TaskConstMeta(
        debugName: "P2PHost_init",
        argNames: [],
      );

  @override
  Future<void> crateP2PHostListen(
      {required P2PHost that, required String addr}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_String(addr, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostListenConstMeta,
      argValues: [that, addr],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostListenConstMeta => const TaskConstMeta(
        debugName: "P2PHost_listen",
        argNames: ["that", "addr"],
      );

  @override
  Future<FlutterPairingResponse> crateP2PHostSendPairingRequest(
      {required P2PHost that,
      required String peer,
      required FlutterPairingRequest req}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_String(peer, serializer);
        sse_encode_box_autoadd_flutter_pairing_request(req, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_flutter_pairing_response,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostSendPairingRequestConstMeta,
      argValues: [that, peer, req],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostSendPairingRequestConstMeta =>
      const TaskConstMeta(
        debugName: "P2PHost_send_pairing_request",
        argNames: ["that", "peer", "req"],
      );

  @override
  Future<void> crateInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_P2PHost => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_P2PHost => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  P2PHost
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return P2PHostImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  P2PHost
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return P2PHostImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  P2PHost
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return P2PHostImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FlutterPairingRequest dco_decode_box_autoadd_flutter_pairing_request(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_pairing_request(raw);
  }

  @protected
  FlutterDiscoverResult dco_decode_flutter_discover_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return FlutterDiscoverResult(
      peers: dco_decode_list_flutter_discovered_peer(arr[0]),
    );
  }

  @protected
  FlutterDiscoveredPeer dco_decode_flutter_discovered_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FlutterDiscoveredPeer(
      peerId: dco_decode_String(arr[0]),
      addresses: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  FlutterNetworkStats dco_decode_flutter_network_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FlutterNetworkStats(
      routingTableSize: dco_decode_usize(arr[0]),
      activeRegistrations: dco_decode_usize(arr[1]),
      rendezvousConnected: dco_decode_bool(arr[2]),
    );
  }

  @protected
  FlutterPairingRequest dco_decode_flutter_pairing_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FlutterPairingRequest(
      claimCode: dco_decode_String(arr[0]),
      deviceName: dco_decode_String(arr[1]),
      deviceType: dco_decode_String(arr[2]),
      deviceOs: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  FlutterPairingResponse dco_decode_flutter_pairing_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FlutterPairingResponse(
      success: dco_decode_bool(arr[0]),
      mediaToken: dco_decode_opt_String(arr[1]),
      accessToken: dco_decode_opt_String(arr[2]),
      deviceToken: dco_decode_opt_String(arr[3]),
      error: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<FlutterDiscoveredPeer> dco_decode_list_flutter_discovered_peer(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_flutter_discovered_peer)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  (
    P2PHost,
    String
  ) dco_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_p_2_p_host_string(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          arr[0]),
      dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  P2PHost
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return P2PHostImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  P2PHost
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return P2PHostImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  P2PHost
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return P2PHostImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FlutterPairingRequest sse_decode_box_autoadd_flutter_pairing_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_pairing_request(deserializer));
  }

  @protected
  FlutterDiscoverResult sse_decode_flutter_discover_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peers = sse_decode_list_flutter_discovered_peer(deserializer);
    return FlutterDiscoverResult(peers: var_peers);
  }

  @protected
  FlutterDiscoveredPeer sse_decode_flutter_discovered_peer(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerId = sse_decode_String(deserializer);
    var var_addresses = sse_decode_list_String(deserializer);
    return FlutterDiscoveredPeer(peerId: var_peerId, addresses: var_addresses);
  }

  @protected
  FlutterNetworkStats sse_decode_flutter_network_stats(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_routingTableSize = sse_decode_usize(deserializer);
    var var_activeRegistrations = sse_decode_usize(deserializer);
    var var_rendezvousConnected = sse_decode_bool(deserializer);
    return FlutterNetworkStats(
        routingTableSize: var_routingTableSize,
        activeRegistrations: var_activeRegistrations,
        rendezvousConnected: var_rendezvousConnected);
  }

  @protected
  FlutterPairingRequest sse_decode_flutter_pairing_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_claimCode = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_deviceType = sse_decode_String(deserializer);
    var var_deviceOs = sse_decode_opt_String(deserializer);
    return FlutterPairingRequest(
        claimCode: var_claimCode,
        deviceName: var_deviceName,
        deviceType: var_deviceType,
        deviceOs: var_deviceOs);
  }

  @protected
  FlutterPairingResponse sse_decode_flutter_pairing_response(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_mediaToken = sse_decode_opt_String(deserializer);
    var var_accessToken = sse_decode_opt_String(deserializer);
    var var_deviceToken = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return FlutterPairingResponse(
        success: var_success,
        mediaToken: var_mediaToken,
        accessToken: var_accessToken,
        deviceToken: var_deviceToken,
        error: var_error);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<FlutterDiscoveredPeer> sse_decode_list_flutter_discovered_peer(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FlutterDiscoveredPeer>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_flutter_discovered_peer(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (
    P2PHost,
    String
  ) sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_p_2_p_host_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 =
        sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          P2PHost self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as P2PHostImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          P2PHost self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as P2PHostImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          P2PHost self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as P2PHostImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
      RustStreamSink<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_flutter_pairing_request(
      FlutterPairingRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_pairing_request(self, serializer);
  }

  @protected
  void sse_encode_flutter_discover_result(
      FlutterDiscoverResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_flutter_discovered_peer(self.peers, serializer);
  }

  @protected
  void sse_encode_flutter_discovered_peer(
      FlutterDiscoveredPeer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peerId, serializer);
    sse_encode_list_String(self.addresses, serializer);
  }

  @protected
  void sse_encode_flutter_network_stats(
      FlutterNetworkStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.routingTableSize, serializer);
    sse_encode_usize(self.activeRegistrations, serializer);
    sse_encode_bool(self.rendezvousConnected, serializer);
  }

  @protected
  void sse_encode_flutter_pairing_request(
      FlutterPairingRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.claimCode, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.deviceType, serializer);
    sse_encode_opt_String(self.deviceOs, serializer);
  }

  @protected
  void sse_encode_flutter_pairing_response(
      FlutterPairingResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_opt_String(self.mediaToken, serializer);
    sse_encode_opt_String(self.accessToken, serializer);
    sse_encode_opt_String(self.deviceToken, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_flutter_discovered_peer(
      List<FlutterDiscoveredPeer> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_flutter_discovered_peer(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void
      sse_encode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_p_2_p_host_string(
          (P2PHost, String) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
        self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class P2PHostImpl extends RustOpaque implements P2PHost {
  // Not to be used by end users
  P2PHostImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  P2PHostImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_P2PHost,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_P2PHost,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_P2PHostPtr,
  );

  /// Add a bootstrap peer and initiate DHT bootstrap.
  /// The address should include the peer ID, e.g., "/ip4/1.2.3.4/tcp/4001/p2p/12D3..."
  Future<void> bootstrap({required String addr}) =>
      RustLib.instance.api.crateP2PHostBootstrap(that: this, addr: addr);

  /// Connect to a relay server and request a reservation.
  /// This allows other peers to connect to us through the relay.
  /// The address should include the relay's peer ID, e.g., "/ip4/1.2.3.4/tcp/4001/p2p/12D3..."
  Future<void> connectRelay({required String relayAddr}) => RustLib.instance.api
      .crateP2PHostConnectRelay(that: this, relayAddr: relayAddr);

  Future<void> dial({required String addr}) =>
      RustLib.instance.api.crateP2PHostDial(that: this, addr: addr);

  /// Discover peers in a rendezvous namespace.
  /// Returns the list of discovered peers and their addresses.
  Future<FlutterDiscoverResult> discoverNamespace(
          {required String namespace}) =>
      RustLib.instance.api
          .crateP2PHostDiscoverNamespace(that: this, namespace: namespace);

  Stream<String> eventStream() => RustLib.instance.api.crateP2PHostEventStream(
        that: this,
      );

  /// Get network statistics (routing table size, active registrations, etc.).
  FlutterNetworkStats getNetworkStats() =>
      RustLib.instance.api.crateP2PHostGetNetworkStats(
        that: this,
      );

  Future<void> listen({required String addr}) =>
      RustLib.instance.api.crateP2PHostListen(that: this, addr: addr);

  Future<FlutterPairingResponse> sendPairingRequest(
          {required String peer, required FlutterPairingRequest req}) =>
      RustLib.instance.api
          .crateP2PHostSendPairingRequest(that: this, peer: peer, req: req);
}
