// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1769995448;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'mydia_player_p2p',
    ioDirectory: 'rust/mydia_player_p2p/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateP2PHostDial({required P2PHost that, required String addr});

  Stream<String> crateP2PHostEventStream({required P2PHost that});

  (P2PHost, String) crateP2PHostInit();

  Future<void> crateP2PHostListen(
      {required P2PHost that, required String addr});

  Future<Uint8List> crateP2PHostReadStreamChunk(
      {required P2PHost that, required String streamId, required int size});

  Future<String> crateP2PHostRequestMedia(
      {required P2PHost that, required String peer, required String filePath});

  Future<FlutterPairingResponse> crateP2PHostSendPairingRequest(
      {required P2PHost that,
      required String peer,
      required FlutterPairingRequest req});

  Future<void> crateInitApp();

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_P2PHost;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_P2PHost;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_P2PHostPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateP2PHostDial({required P2PHost that, required String addr}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_String(addr, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostDialConstMeta,
      argValues: [that, addr],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostDialConstMeta => const TaskConstMeta(
        debugName: "P2PHost_dial",
        argNames: ["that", "addr"],
      );

  @override
  Stream<String> crateP2PHostEventStream({required P2PHost that}) {
    final sink = RustStreamSink<String>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_StreamSink_String_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostEventStreamConstMeta,
      argValues: [that, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateP2PHostEventStreamConstMeta => const TaskConstMeta(
        debugName: "P2PHost_event_stream",
        argNames: ["that", "sink"],
      );

  @override
  (P2PHost, String) crateP2PHostInit() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_p_2_p_host_string,
        decodeErrorData: null,
      ),
      constMeta: kCrateP2PHostInitConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostInitConstMeta => const TaskConstMeta(
        debugName: "P2PHost_init",
        argNames: [],
      );

  @override
  Future<void> crateP2PHostListen(
      {required P2PHost that, required String addr}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_String(addr, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostListenConstMeta,
      argValues: [that, addr],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostListenConstMeta => const TaskConstMeta(
        debugName: "P2PHost_listen",
        argNames: ["that", "addr"],
      );

  @override
  Future<Uint8List> crateP2PHostReadStreamChunk(
      {required P2PHost that, required String streamId, required int size}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_String(streamId, serializer);
        sse_encode_u_32(size, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostReadStreamChunkConstMeta,
      argValues: [that, streamId, size],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostReadStreamChunkConstMeta =>
      const TaskConstMeta(
        debugName: "P2PHost_read_stream_chunk",
        argNames: ["that", "streamId", "size"],
      );

  @override
  Future<String> crateP2PHostRequestMedia(
      {required P2PHost that, required String peer, required String filePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_String(peer, serializer);
        sse_encode_String(filePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostRequestMediaConstMeta,
      argValues: [that, peer, filePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostRequestMediaConstMeta => const TaskConstMeta(
        debugName: "P2PHost_request_media",
        argNames: ["that", "peer", "filePath"],
      );

  @override
  Future<FlutterPairingResponse> crateP2PHostSendPairingRequest(
      {required P2PHost that,
      required String peer,
      required FlutterPairingRequest req}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_String(peer, serializer);
        sse_encode_box_autoadd_flutter_pairing_request(req, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_flutter_pairing_response,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostSendPairingRequestConstMeta,
      argValues: [that, peer, req],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostSendPairingRequestConstMeta =>
      const TaskConstMeta(
        debugName: "P2PHost_send_pairing_request",
        argNames: ["that", "peer", "req"],
      );

  @override
  Future<void> crateInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_P2PHost => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_P2PHost => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  P2PHost
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return P2PHostImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  P2PHost
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return P2PHostImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  P2PHost
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return P2PHostImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FlutterPairingRequest dco_decode_box_autoadd_flutter_pairing_request(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_pairing_request(raw);
  }

  @protected
  FlutterPairingRequest dco_decode_flutter_pairing_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FlutterPairingRequest(
      claimCode: dco_decode_String(arr[0]),
      deviceName: dco_decode_String(arr[1]),
      deviceType: dco_decode_String(arr[2]),
      deviceOs: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  FlutterPairingResponse dco_decode_flutter_pairing_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FlutterPairingResponse(
      success: dco_decode_bool(arr[0]),
      mediaToken: dco_decode_opt_String(arr[1]),
      accessToken: dco_decode_opt_String(arr[2]),
      deviceToken: dco_decode_opt_String(arr[3]),
      error: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  (
    P2PHost,
    String
  ) dco_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_p_2_p_host_string(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          arr[0]),
      dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  P2PHost
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return P2PHostImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  P2PHost
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return P2PHostImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  P2PHost
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return P2PHostImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FlutterPairingRequest sse_decode_box_autoadd_flutter_pairing_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_pairing_request(deserializer));
  }

  @protected
  FlutterPairingRequest sse_decode_flutter_pairing_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_claimCode = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_deviceType = sse_decode_String(deserializer);
    var var_deviceOs = sse_decode_opt_String(deserializer);
    return FlutterPairingRequest(
        claimCode: var_claimCode,
        deviceName: var_deviceName,
        deviceType: var_deviceType,
        deviceOs: var_deviceOs);
  }

  @protected
  FlutterPairingResponse sse_decode_flutter_pairing_response(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_mediaToken = sse_decode_opt_String(deserializer);
    var var_accessToken = sse_decode_opt_String(deserializer);
    var var_deviceToken = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return FlutterPairingResponse(
        success: var_success,
        mediaToken: var_mediaToken,
        accessToken: var_accessToken,
        deviceToken: var_deviceToken,
        error: var_error);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (
    P2PHost,
    String
  ) sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_p_2_p_host_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 =
        sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          P2PHost self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as P2PHostImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          P2PHost self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as P2PHostImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          P2PHost self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as P2PHostImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
      RustStreamSink<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_flutter_pairing_request(
      FlutterPairingRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_pairing_request(self, serializer);
  }

  @protected
  void sse_encode_flutter_pairing_request(
      FlutterPairingRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.claimCode, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.deviceType, serializer);
    sse_encode_opt_String(self.deviceOs, serializer);
  }

  @protected
  void sse_encode_flutter_pairing_response(
      FlutterPairingResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_opt_String(self.mediaToken, serializer);
    sse_encode_opt_String(self.accessToken, serializer);
    sse_encode_opt_String(self.deviceToken, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void
      sse_encode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_p_2_p_host_string(
          (P2PHost, String) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
        self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class P2PHostImpl extends RustOpaque implements P2PHost {
  // Not to be used by end users
  P2PHostImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  P2PHostImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_P2PHost,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_P2PHost,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_P2PHostPtr,
  );

  Future<void> dial({required String addr}) =>
      RustLib.instance.api.crateP2PHostDial(that: this, addr: addr);

  Stream<String> eventStream() => RustLib.instance.api.crateP2PHostEventStream(
        that: this,
      );

  Future<void> listen({required String addr}) =>
      RustLib.instance.api.crateP2PHostListen(that: this, addr: addr);

  Future<Uint8List> readStreamChunk(
          {required String streamId, required int size}) =>
      RustLib.instance.api.crateP2PHostReadStreamChunk(
          that: this, streamId: streamId, size: size);

  Future<String> requestMedia(
          {required String peer, required String filePath}) =>
      RustLib.instance.api
          .crateP2PHostRequestMedia(that: this, peer: peer, filePath: filePath);

  Future<FlutterPairingResponse> sendPairingRequest(
          {required String peer, required FlutterPairingRequest req}) =>
      RustLib.instance.api
          .crateP2PHostSendPairingRequest(that: this, peer: peer, req: req);
}
