// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<P2pHost>>
abstract class P2PHost implements RustOpaqueInterface {
  Future<void> dial({required String addr});

  Stream<String> eventStream();

  static (P2PHost, String) init() => RustLib.instance.api.crateP2PHostInit();

  Future<void> listen({required String addr});
}
