// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<P2pHost>>
abstract class P2PHost implements RustOpaqueInterface {
  /// Add a bootstrap peer and initiate DHT bootstrap.
  /// The address should include the peer ID, e.g., "/ip4/1.2.3.4/tcp/4001/p2p/12D3..."
  Future<void> bootstrap({required String addr});

  /// Connect to a relay server and request a reservation.
  /// This allows other peers to connect to us through the relay.
  /// The address should include the relay's peer ID, e.g., "/ip4/1.2.3.4/tcp/4001/p2p/12D3..."
  Future<void> connectRelay({required String relayAddr});

  Future<void> dial({required String addr});

  /// Discover peers in a rendezvous namespace.
  /// Returns the list of discovered peers and their addresses.
  Future<FlutterDiscoverResult> discoverNamespace({required String namespace});

  Stream<String> eventStream();

  /// Get network statistics (routing table size, active registrations, etc.).
  FlutterNetworkStats getNetworkStats();

  static (P2PHost, String) init() => RustLib.instance.api.crateP2PHostInit();

  Future<void> listen({required String addr});

  Future<FlutterPairingResponse> sendPairingRequest(
      {required String peer, required FlutterPairingRequest req});
}

/// Result of a rendezvous discovery
class FlutterDiscoverResult {
  final List<FlutterDiscoveredPeer> peers;

  const FlutterDiscoverResult({
    required this.peers,
  });

  @override
  int get hashCode => peers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterDiscoverResult &&
          runtimeType == other.runtimeType &&
          peers == other.peers;
}

class FlutterDiscoveredPeer {
  final String peerId;
  final List<String> addresses;

  const FlutterDiscoveredPeer({
    required this.peerId,
    required this.addresses,
  });

  @override
  int get hashCode => peerId.hashCode ^ addresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterDiscoveredPeer &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          addresses == other.addresses;
}

/// Network statistics for display in the UI
class FlutterNetworkStats {
  final BigInt routingTableSize;
  final BigInt activeRegistrations;
  final bool rendezvousConnected;

  const FlutterNetworkStats({
    required this.routingTableSize,
    required this.activeRegistrations,
    required this.rendezvousConnected,
  });

  @override
  int get hashCode =>
      routingTableSize.hashCode ^
      activeRegistrations.hashCode ^
      rendezvousConnected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterNetworkStats &&
          runtimeType == other.runtimeType &&
          routingTableSize == other.routingTableSize &&
          activeRegistrations == other.activeRegistrations &&
          rendezvousConnected == other.rendezvousConnected;
}

class FlutterPairingRequest {
  final String claimCode;
  final String deviceName;
  final String deviceType;
  final String? deviceOs;

  const FlutterPairingRequest({
    required this.claimCode,
    required this.deviceName,
    required this.deviceType,
    this.deviceOs,
  });

  @override
  int get hashCode =>
      claimCode.hashCode ^
      deviceName.hashCode ^
      deviceType.hashCode ^
      deviceOs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterPairingRequest &&
          runtimeType == other.runtimeType &&
          claimCode == other.claimCode &&
          deviceName == other.deviceName &&
          deviceType == other.deviceType &&
          deviceOs == other.deviceOs;
}

class FlutterPairingResponse {
  final bool success;
  final String? mediaToken;
  final String? accessToken;
  final String? deviceToken;
  final String? error;

  const FlutterPairingResponse({
    required this.success,
    this.mediaToken,
    this.accessToken,
    this.deviceToken,
    this.error,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      mediaToken.hashCode ^
      accessToken.hashCode ^
      deviceToken.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterPairingResponse &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          mediaToken == other.mediaToken &&
          accessToken == other.accessToken &&
          deviceToken == other.deviceToken &&
          error == other.error;
}
