defmodule MetadataRelay.Relay.Claim do
  @moduledoc """
  Schema for relay claim codes - temporary codes for device pairing.

  Claim codes are generated by Mydia instances and allow clients to
  pair with the instance through the relay. The flow:

  1. Admin generates claim code in Mydia web UI
  2. Mydia registers the claim code with the relay
  3. User enters code in Flutter app
  4. App redeems the code to get instance info for pairing
  5. Code is marked as consumed after successful pairing

  Codes are:
  - 6-8 alphanumeric characters (case-insensitive)
  - Valid for a limited time (typically 5 minutes)
  - Single-use
  """
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  # Default expiration: 5 minutes
  @default_ttl_seconds 300

  schema "relay_claims" do
    field :code, :string
    field :user_id, :string
    field :expires_at, :utc_datetime
    field :consumed_at, :utc_datetime
    field :consumed_by_device_id, :string

    belongs_to :instance, MetadataRelay.Relay.Instance

    timestamps(type: :utc_datetime)
  end

  @doc """
  Changeset for creating a new claim code.
  """
  def create_changeset(claim, attrs) do
    claim
    |> cast(attrs, [:code, :user_id, :instance_id, :expires_at])
    |> validate_required([:code, :user_id, :instance_id])
    |> validate_length(:code, min: 6, max: 8)
    |> validate_format(:code, ~r/^[A-Z0-9]+$/i, message: "must be alphanumeric")
    |> put_default_expiration()
    |> unique_constraint(:code)
    |> foreign_key_constraint(:instance_id)
  end

  @doc """
  Changeset for consuming a claim code.
  """
  def consume_changeset(claim, device_id) do
    now = DateTime.utc_now() |> DateTime.truncate(:second)

    claim
    |> change(consumed_at: now, consumed_by_device_id: device_id)
  end

  @doc """
  Checks if a claim code has expired.
  """
  def expired?(%__MODULE__{expires_at: expires_at}) do
    DateTime.compare(DateTime.utc_now(), expires_at) == :gt
  end

  @doc """
  Checks if a claim code has been consumed.
  """
  def consumed?(%__MODULE__{consumed_at: consumed_at}) do
    not is_nil(consumed_at)
  end

  @doc """
  Checks if a claim code is valid (not expired and not consumed).
  """
  def valid?(claim) do
    not expired?(claim) and not consumed?(claim)
  end

  @doc """
  Generates a random claim code.
  """
  def generate_code(length \\ 6) do
    alphabet = ~c"ABCDEFGHJKLMNPQRSTUVWXYZ23456789"

    1..length
    |> Enum.map(fn _ -> Enum.random(alphabet) end)
    |> List.to_string()
  end

  defp put_default_expiration(changeset) do
    case get_field(changeset, :expires_at) do
      nil ->
        expires_at =
          DateTime.utc_now()
          |> DateTime.add(@default_ttl_seconds, :second)
          |> DateTime.truncate(:second)

        put_change(changeset, :expires_at, expires_at)

      _ ->
        changeset
    end
  end
end
