// Mocks generated by Mockito 5.4.6 from annotations
// in player/test/core/connection/direct_prober_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:phoenix_socket/phoenix_socket.dart' as _i4;
import 'package:player/core/channels/channel_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeChannelResult_0<T> extends _i1.SmartFake
    implements _i2.ChannelResult<T> {
  _FakeChannelResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ChannelService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannelService extends _i1.Mock implements _i2.ChannelService {
  MockChannelService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<_i2.ChannelResult<void>> connect(String? serverUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [serverUrl],
        ),
        returnValue: _i3.Future<_i2.ChannelResult<void>>.value(
            _FakeChannelResult_0<void>(
          this,
          Invocation.method(
            #connect,
            [serverUrl],
          ),
        )),
      ) as _i3.Future<_i2.ChannelResult<void>>);

  @override
  _i3.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i2.ChannelResult<_i4.PhoenixChannel>> joinPairingChannel() =>
      (super.noSuchMethod(
        Invocation.method(
          #joinPairingChannel,
          [],
        ),
        returnValue: _i3.Future<_i2.ChannelResult<_i4.PhoenixChannel>>.value(
            _FakeChannelResult_0<_i4.PhoenixChannel>(
          this,
          Invocation.method(
            #joinPairingChannel,
            [],
          ),
        )),
      ) as _i3.Future<_i2.ChannelResult<_i4.PhoenixChannel>>);

  @override
  _i3.Future<_i2.ChannelResult<_i4.PhoenixChannel>> joinReconnectChannel() =>
      (super.noSuchMethod(
        Invocation.method(
          #joinReconnectChannel,
          [],
        ),
        returnValue: _i3.Future<_i2.ChannelResult<_i4.PhoenixChannel>>.value(
            _FakeChannelResult_0<_i4.PhoenixChannel>(
          this,
          Invocation.method(
            #joinReconnectChannel,
            [],
          ),
        )),
      ) as _i3.Future<_i2.ChannelResult<_i4.PhoenixChannel>>);

  @override
  _i3.Future<_i2.ChannelResult<void>> joinProbeChannel() => (super.noSuchMethod(
        Invocation.method(
          #joinProbeChannel,
          [],
        ),
        returnValue: _i3.Future<_i2.ChannelResult<void>>.value(
            _FakeChannelResult_0<void>(
          this,
          Invocation.method(
            #joinProbeChannel,
            [],
          ),
        )),
      ) as _i3.Future<_i2.ChannelResult<void>>);

  @override
  _i3.Future<_i2.ChannelResult<_i5.Uint8List>> sendPairingHandshake(
    _i4.PhoenixChannel? channel,
    _i5.Uint8List? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPairingHandshake,
          [
            channel,
            message,
          ],
        ),
        returnValue: _i3.Future<_i2.ChannelResult<_i5.Uint8List>>.value(
            _FakeChannelResult_0<_i5.Uint8List>(
          this,
          Invocation.method(
            #sendPairingHandshake,
            [
              channel,
              message,
            ],
          ),
        )),
      ) as _i3.Future<_i2.ChannelResult<_i5.Uint8List>>);

  @override
  _i3.Future<_i2.ChannelResult<_i2.ReconnectResponse>> sendReconnectHandshake(
    _i4.PhoenixChannel? channel,
    _i5.Uint8List? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendReconnectHandshake,
          [
            channel,
            message,
          ],
        ),
        returnValue: _i3.Future<_i2.ChannelResult<_i2.ReconnectResponse>>.value(
            _FakeChannelResult_0<_i2.ReconnectResponse>(
          this,
          Invocation.method(
            #sendReconnectHandshake,
            [
              channel,
              message,
            ],
          ),
        )),
      ) as _i3.Future<_i2.ChannelResult<_i2.ReconnectResponse>>);

  @override
  _i3.Future<_i2.ChannelResult<_i2.KeyExchangeResponse>> sendKeyExchange(
    _i4.PhoenixChannel? channel,
    String? clientPublicKey,
    String? deviceToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendKeyExchange,
          [
            channel,
            clientPublicKey,
            deviceToken,
          ],
        ),
        returnValue:
            _i3.Future<_i2.ChannelResult<_i2.KeyExchangeResponse>>.value(
                _FakeChannelResult_0<_i2.KeyExchangeResponse>(
          this,
          Invocation.method(
            #sendKeyExchange,
            [
              channel,
              clientPublicKey,
              deviceToken,
            ],
          ),
        )),
      ) as _i3.Future<_i2.ChannelResult<_i2.KeyExchangeResponse>>);

  @override
  _i3.Future<_i2.ChannelResult<_i2.PairingResponse>> submitClaimCode(
    _i4.PhoenixChannel? channel, {
    required String? claimCode,
    required String? deviceName,
    required String? platform,
    required String? staticPublicKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitClaimCode,
          [channel],
          {
            #claimCode: claimCode,
            #deviceName: deviceName,
            #platform: platform,
            #staticPublicKey: staticPublicKey,
          },
        ),
        returnValue: _i3.Future<_i2.ChannelResult<_i2.PairingResponse>>.value(
            _FakeChannelResult_0<_i2.PairingResponse>(
          this,
          Invocation.method(
            #submitClaimCode,
            [channel],
            {
              #claimCode: claimCode,
              #deviceName: deviceName,
              #platform: platform,
              #staticPublicKey: staticPublicKey,
            },
          ),
        )),
      ) as _i3.Future<_i2.ChannelResult<_i2.PairingResponse>>);
}
