// Mocks generated by Mockito 5.4.6 from annotations
// in player/test/core/connection/relay_first_connection_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:phoenix_socket/phoenix_socket.dart' as _i5;
import 'package:player/core/channels/channel_service.dart' as _i2;
import 'package:player/core/relay/relay_tunnel_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeChannelResult_0<T> extends _i1.SmartFake
    implements _i2.ChannelResult<T> {
  _FakeChannelResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRelayTunnelInfo_1 extends _i1.SmartFake
    implements _i3.RelayTunnelInfo {
  _FakeRelayTunnelInfo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTunnelResponse_2 extends _i1.SmartFake
    implements _i3.TunnelResponse {
  _FakeTunnelResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ChannelService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannelService extends _i1.Mock implements _i2.ChannelService {
  MockChannelService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<_i2.ChannelResult<void>> connect(String? serverUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [serverUrl],
        ),
        returnValue: _i4.Future<_i2.ChannelResult<void>>.value(
            _FakeChannelResult_0<void>(
          this,
          Invocation.method(
            #connect,
            [serverUrl],
          ),
        )),
      ) as _i4.Future<_i2.ChannelResult<void>>);

  @override
  _i4.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.ChannelResult<_i5.PhoenixChannel>> joinPairingChannel() =>
      (super.noSuchMethod(
        Invocation.method(
          #joinPairingChannel,
          [],
        ),
        returnValue: _i4.Future<_i2.ChannelResult<_i5.PhoenixChannel>>.value(
            _FakeChannelResult_0<_i5.PhoenixChannel>(
          this,
          Invocation.method(
            #joinPairingChannel,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ChannelResult<_i5.PhoenixChannel>>);

  @override
  _i4.Future<_i2.ChannelResult<_i5.PhoenixChannel>> joinReconnectChannel() =>
      (super.noSuchMethod(
        Invocation.method(
          #joinReconnectChannel,
          [],
        ),
        returnValue: _i4.Future<_i2.ChannelResult<_i5.PhoenixChannel>>.value(
            _FakeChannelResult_0<_i5.PhoenixChannel>(
          this,
          Invocation.method(
            #joinReconnectChannel,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ChannelResult<_i5.PhoenixChannel>>);

  @override
  _i4.Future<_i2.ChannelResult<void>> joinProbeChannel() => (super.noSuchMethod(
        Invocation.method(
          #joinProbeChannel,
          [],
        ),
        returnValue: _i4.Future<_i2.ChannelResult<void>>.value(
            _FakeChannelResult_0<void>(
          this,
          Invocation.method(
            #joinProbeChannel,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ChannelResult<void>>);

  @override
  _i4.Future<_i2.ChannelResult<_i6.Uint8List>> sendPairingHandshake(
    _i5.PhoenixChannel? channel,
    _i6.Uint8List? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPairingHandshake,
          [
            channel,
            message,
          ],
        ),
        returnValue: _i4.Future<_i2.ChannelResult<_i6.Uint8List>>.value(
            _FakeChannelResult_0<_i6.Uint8List>(
          this,
          Invocation.method(
            #sendPairingHandshake,
            [
              channel,
              message,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ChannelResult<_i6.Uint8List>>);

  @override
  _i4.Future<_i2.ChannelResult<_i2.ReconnectResponse>> sendReconnectHandshake(
    _i5.PhoenixChannel? channel,
    _i6.Uint8List? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendReconnectHandshake,
          [
            channel,
            message,
          ],
        ),
        returnValue: _i4.Future<_i2.ChannelResult<_i2.ReconnectResponse>>.value(
            _FakeChannelResult_0<_i2.ReconnectResponse>(
          this,
          Invocation.method(
            #sendReconnectHandshake,
            [
              channel,
              message,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ChannelResult<_i2.ReconnectResponse>>);

  @override
  _i4.Future<_i2.ChannelResult<_i2.KeyExchangeResponse>> sendKeyExchange(
    _i5.PhoenixChannel? channel,
    String? clientPublicKey,
    String? deviceToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendKeyExchange,
          [
            channel,
            clientPublicKey,
            deviceToken,
          ],
        ),
        returnValue:
            _i4.Future<_i2.ChannelResult<_i2.KeyExchangeResponse>>.value(
                _FakeChannelResult_0<_i2.KeyExchangeResponse>(
          this,
          Invocation.method(
            #sendKeyExchange,
            [
              channel,
              clientPublicKey,
              deviceToken,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ChannelResult<_i2.KeyExchangeResponse>>);

  @override
  _i4.Future<_i2.ChannelResult<_i2.PairingResponse>> submitClaimCode(
    _i5.PhoenixChannel? channel, {
    required String? claimCode,
    required String? deviceName,
    required String? platform,
    required String? staticPublicKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitClaimCode,
          [channel],
          {
            #claimCode: claimCode,
            #deviceName: deviceName,
            #platform: platform,
            #staticPublicKey: staticPublicKey,
          },
        ),
        returnValue: _i4.Future<_i2.ChannelResult<_i2.PairingResponse>>.value(
            _FakeChannelResult_0<_i2.PairingResponse>(
          this,
          Invocation.method(
            #submitClaimCode,
            [channel],
            {
              #claimCode: claimCode,
              #deviceName: deviceName,
              #platform: platform,
              #staticPublicKey: staticPublicKey,
            },
          ),
        )),
      ) as _i4.Future<_i2.ChannelResult<_i2.PairingResponse>>);
}

/// A class which mocks [RelayTunnel].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelayTunnel extends _i1.Mock implements _i3.RelayTunnel {
  MockRelayTunnel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isEncryptionEnabled => (super.noSuchMethod(
        Invocation.getter(#isEncryptionEnabled),
        returnValue: false,
      ) as bool);

  @override
  _i3.RelayTunnelInfo get info => (super.noSuchMethod(
        Invocation.getter(#info),
        returnValue: _FakeRelayTunnelInfo_1(
          this,
          Invocation.getter(#info),
        ),
      ) as _i3.RelayTunnelInfo);

  @override
  _i4.Stream<_i6.Uint8List> get messages => (super.noSuchMethod(
        Invocation.getter(#messages),
        returnValue: _i4.Stream<_i6.Uint8List>.empty(),
      ) as _i4.Stream<_i6.Uint8List>);

  @override
  _i4.Stream<String> get errors => (super.noSuchMethod(
        Invocation.getter(#errors),
        returnValue: _i4.Stream<String>.empty(),
      ) as _i4.Stream<String>);

  @override
  bool get isActive => (super.noSuchMethod(
        Invocation.getter(#isActive),
        returnValue: false,
      ) as bool);

  @override
  void enableEncryption(_i6.Uint8List? sessionKeyBytes) => super.noSuchMethod(
        Invocation.method(
          #enableEncryption,
          [sessionKeyBytes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> sendJsonMessage(String? jsonMessage) => (super.noSuchMethod(
        Invocation.method(
          #sendJsonMessage,
          [jsonMessage],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void sendMessage(_i6.Uint8List? payload) => super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [payload],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.TunnelResponse> request({
    required String? method,
    required String? path,
    Map<String, String>? headers,
    String? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [],
          {
            #method: method,
            #path: path,
            #headers: headers,
            #body: body,
          },
        ),
        returnValue: _i4.Future<_i3.TunnelResponse>.value(_FakeTunnelResponse_2(
          this,
          Invocation.method(
            #request,
            [],
            {
              #method: method,
              #path: path,
              #headers: headers,
              #body: body,
            },
          ),
        )),
      ) as _i4.Future<_i3.TunnelResponse>);
}

/// A class which mocks [RelayTunnelInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelayTunnelInfo extends _i1.Mock implements _i3.RelayTunnelInfo {
  MockRelayTunnelInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get sessionId => (super.noSuchMethod(
        Invocation.getter(#sessionId),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#sessionId),
        ),
      ) as String);

  @override
  String get instanceId => (super.noSuchMethod(
        Invocation.getter(#instanceId),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#instanceId),
        ),
      ) as String);

  @override
  String get publicKey => (super.noSuchMethod(
        Invocation.getter(#publicKey),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#publicKey),
        ),
      ) as String);

  @override
  List<String> get directUrls => (super.noSuchMethod(
        Invocation.getter(#directUrls),
        returnValue: <String>[],
      ) as List<String>);
}
