name: Docker Build

on:
  push:
    branches: [master, main]
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - db: sqlite
            tag: master
          - db: postgres
            tag: master-pg

    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: useblacksmith/setup-docker-builder@v1

      - uses: docker/login-action@v3
        if: github.event_name == 'push'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.db }}
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: DATABASE_TYPE=${{ matrix.db }}
          push: ${{ github.event_name == 'push' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.tag }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache-${{ matrix.db }}
          cache-to: ${{ github.event_name == 'push' && format('type=registry,ref={0}/{1}:cache-{2},mode=max', env.REGISTRY, env.IMAGE_NAME, matrix.db) || '' }}
